### ISSUE TITLE
nim service deployment fails when "nvidia.com/gpu" toleration is specified

### ISSUE THREAD

**Issue by nmartorell** [NVIDIA/k8s-nim-operator#288]
### 1. Quick Debug Information
* OS/Version(e.g. RHEL8.6, Ubuntu22.04): AL2023 (AMI amazon-eks-node-al2023-x86_64-nvidia-1.30-v20250103)
* Container Runtime Type/Version(e.g. Containerd, CRI-O, Docker): containerd
* K8s Flavor/Version(e.g. K8s, OCP, Rancher, GKE, EKS): EKS (v1.30)
* GPU Operator Version: v24.9.1
* NIM Operator Version: 1.0.1
* LLM NIM Versions: N/A
* NeMo Service Versions: N/A

### 2. Issue or feature description
NIM Service fails to start when a toleration with key "nvidia.com/gpu" is specified.

### 3. Steps to reproduce the issue
Deploy a NIM Service with the following YAML:
```
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: meta-llama3-8b-instruct
  namespace: nim-service
spec:
  image:
    repository: nvcr.io/nim/meta/llama3-8b-instruct
    tag: 1.0.3
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    pvc:
      create: true
      storageClass: efs-sc
      size: 30Gi
      volumeAccessMode: ReadWriteMany
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: 1
  expose:
    service:
      type: ClusterIP
```

### 4. Information to attach

The NIM Service pod fails to start, the only event in the logs is:
`error converting unstructured object to Deployment: unrecognized type: string`

The NIM Operator pod logs show the following error:
```
github.com/NVIDIA/k8s-nim-operator/internal/controller/platform/standalone.(*NIMServiceReconciler).renderAndSyncResource
	/workspace/internal/controller/platform/standalone/nimservice.go:285
github.com/NVIDIA/k8s-nim-operator/internal/controller/platform/standalone.(*NIMServiceReconciler).reconcileNIMService
	/workspace/internal/controller/platform/standalone/nimservice.go:245
github.com/NVIDIA/k8s-nim-operator/internal/controller/platform/standalone.(*Standalone).Sync
	/workspace/internal/controller/platform/standalone/standalone.go:115
github.com/NVIDIA/k8s-nim-operator/internal/controller.(*NIMServiceReconciler).Reconcile
	/workspace/internal/controller/nimservice_controller.go:158
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:116
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224
2025-01-17T20:14:19Z	DEBUG	events	NIMService metallama38binstruct2 failed, msg: error converting unstructured object to Deployment: unrecognized type: string	{"type": "Warning", "object": {"kind":"NIMService","namespace":"nim-service","name":"metallama38binstruct2","uid":"a0fb54b7-e4c5-4caa-a99f-cf29bf09f929","apiVersion":"apps.nvidia.com/v1alpha1","resourceVersion":"78747"}, "reason": "Failed"}
2025-01-17T20:14:19Z	DEBUG	events	NIMService metallama38binstruct2 failed, msg: error converting unstructured object to Deployment: unrecognized type: string	{"type": "Warning", "object": {"kind":"NIMService","namespace":"nim-service","name":"metallama38binstruct2","uid":"a0fb54b7-e4c5-4caa-a99f-cf29bf09f929","apiVersion":"apps.nvidia.com/v1alpha1","resourceVersion":"78747"}, "reason": "ReconcileFailed"}
2025-01-17T20:14:19Z	ERROR	controllers.NIMService	Unable to update status	{"error": "error converting unstructured object to Deployment: unrecognized type: string"}
```

I;m not sure, but I think that the issue is that the NIM Operator is automatically adding a toleration with the same key (i.e. when I `kubectl edit` a NIM Service pod that successfully starts (i.e. when I don't manually add the toleration to the yaml file), I can see the following toleration automatically added):
```
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
```
