### ISSUE TITLE
NeMo dependencies fail to install (postgres)

### ISSUE THREAD

**Issue by nmartorell** [NVIDIA/k8s-nim-operator#502]
I'm attempting to run through the NeMo microservices installation via the NIM Operator, as described in the docs [here](https://docs.nvidia.com/nim-operator/latest/nemo-prerequisites.html#). I'm facing an issue with the ansible playbook to install the dependencies.

The values.yaml file I'm using is the following (note that the storage class is an AWS EFS, and I'm only trying to install the evaluator):

```
install:
  customizer: no
  datastore: no
  entity_store: no
  evaluator: yes
  jupyter: no

uninstall:
  customizer: yes
  datastore: yes
  entity_store: yes
  evaluator: yes
  jupyter: yes

installation_namespace: nemo

# Specify a custom storage class and volume access mode for all PVCs, for e.g. ReadWriteMany for nfs storage class
pvc:
  # Ignored when localPathProvisioner.enabled is true — in which case these will default to:
  # storage_class: "local-path" and volume_access_mode: "ReadWriteOnce"
  storage_class: "efs-sc"
  volume_access_mode: ReadWriteMany

# Deploy a local-path CSI provisioner
localPathProvisioner:
  # disable it when a different CSI provisioner is already deployed in the cluster
  enabled: false
  default: true
  version: v0.0.31
```

Then, I run the playbook, which fails due to the postgres pod not becoming ready. As far as I can tell, the postgres pod fails within a second or two, so I can't exec into it to see what the issue is.

The logs don't give me much info either:
```
postgresql 21:39:39.37 INFO  ==> 
postgresql 21:39:39.37 INFO  ==> Welcome to the Bitnami postgresql container
postgresql 21:39:39.38 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
postgresql 21:39:39.38 INFO  ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
postgresql 21:39:39.38 INFO  ==> 
postgresql 21:39:39.48 INFO  ==> ** Starting PostgreSQL setup **
postgresql 21:39:39.49 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 21:39:39.58 INFO  ==> Loading custom pre-init scripts...
postgresql 21:39:39.59 INFO  ==> Initializing PostgreSQL database...
postgresql 21:39:39.69 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 21:39:39.69 INFO  ==> Generating local authentication configuration
```

The pod events also aren't too helpful:
```
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  39m                    default-scheduler  0/2 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
  Normal   Scheduled         39m                    default-scheduler  Successfully assigned nemo/evaluator-pg-postgresql-0 to ip-192-168-2-120.us-east-2.compute.internal
  Normal   Pulled            37m (x5 over 39m)      kubelet            Container image "docker.io/bitnami/postgresql:17.5.0-debian-12-r3" already present on machine
  Normal   Created           37m (x5 over 39m)      kubelet            Created container: postgresql
  Normal   Started           37m (x5 over 39m)      kubelet            Started container postgresql
  Warning  BackOff           3m53s (x170 over 38m)  kubelet            Back-off restarting failed container postgresql in pod evaluator-pg-postgresql-0_nemo(48ddcd0a-562a-4075-b220-d826b9d52326)
```

Any idea on what could go going on?
